name: cd-main
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}   # ← para dispararlo manualmente desde Actions
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # OIDC para WIF
      contents: read
    env:
      IMG_TAG: ${{ github.sha }}
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Install Poetry
        run: pip install "poetry==1.8.3"

      # Auth GCP vía WIF
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Docker login to Artifact Registry
        run: |
          REG_HOST="$(echo "${{ secrets.AR_REPO }}" | cut -d/ -f1)"
          gcloud auth configure-docker "$REG_HOST" -q

      - name: Build & Push image
        run: |
          docker build -f deploy/Dockerfile -t "${{ secrets.AR_REPO }}/news-semantic-api:${IMG_TAG}" .
          docker push "${{ secrets.AR_REPO }}/news-semantic-api:${IMG_TAG}"

      - uses: azure/setup-kubectl@v4
      - uses: azure/setup-helm@v4

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials "${{ secrets.GKE_CLUSTER }}" --region "${{ secrets.GKE_REGION }}" --project "${{ secrets.GCP_PROJECT }}"

      - name: Helm upgrade (API + Qdrant subchart)
        working-directory: deploy/helm/news-semantic-api
        run: |
          helm repo add qdrant https://qdrant.github.io/qdrant-helm || true
          helm repo update && helm dependency update
          helm upgrade --install news-demo . \
            --set image.repository="${{ secrets.AR_REPO }}/news-semantic-api" \
            --set image.tag="${IMG_TAG}" \
            -f values.gke.yaml
