name: ci-pr

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps (poetry)
        run: |
          python -m pip install --upgrade pip
          pip install "poetry==1.8.3"
          poetry config virtualenvs.create false
          poetry install --with dev
      - name: Lint (ruff opcional)
        run: |
          pip install ruff
          ruff check .
      - name: Run tests
        run: pytest -q
