name: ci-pr
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}   # ← permite lanzarlo manualmente desde Actions 
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install Poetry
        run: pip install "poetry==1.8.3"
      - name: Install deps
        run: poetry install --no-interaction
      - name: Lint
        run: poetry run ruff check .
      - name: Format check
        run: poetry run ruff format --check .
      - name: Type check
        run: poetry run mypy .
      - name: Tests
        run: poetry run pytest -q
