name: tf-apply

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: gcp-dev
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: infra/terraform/gcp/dev

    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
