name: tf-plan

on:
  pull_request:
    paths:
      - 'infra/**'
  workflow_dispatch: {}

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: infra/terraform/gcp/dev
    env:
      TF_IN_AUTOMATION: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -lock-timeout=60s -no-color -out=tfplan

      - name: Human-readable plan
        run: terraform show -no-color tfplan > plan.txt

      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            infra/terraform/gcp/dev/tfplan
            infra/terraform/gcp/dev/plan.txt
